# permissions for end users to edit varnishes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: varnish-editor-role
rules:
- apiGroups:
  - cache.docker.io
  resources:
  - varnishes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.docker.io
  resources:
  - varnishes/status
  verbs:
  - get
