# permissions for end users to view varnishes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: varnish-viewer-role
rules:
- apiGroups:
  - cache.docker.io
  resources:
  - varnishes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.docker.io
  resources:
  - varnishes/status
  verbs:
  - get
